name: Minify funnelQuest.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Terser
        run: npm install terser

      - name: Minify funnelQuest.js
        run: npx terser funnelQuest.js -o funnelQuest.min.js

      - name: Commit minified file
        run: |
          git config --local user.email "erayalakese@users.noreply.github.com"
          git config --local user.name "Eray Alakese"
          git add funnelQuest.min.js
          if ! git diff --staged --quiet; then
            git commit -m "Update minified funnelQuest.js [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
